In [17]:
import os
import duckdb
import polars as pl

DATA_PATH = "../data/raw/Border_Crossing_Entry_Data.csv"
OUTPUT_DIR = "../data/processed"
os.makedirs(OUTPUT_DIR, exist_ok=True)

print(f"Path dataset: {DATA_PATH}")
print(f"Status file: {'Ditemukan' if os.path.exists(DATA_PATH) else 'TIDAK DITEMUKAN - Cek path!'}")

Path dataset: ../data/raw/Border_Crossing_Entry_Data.csv
Status file: Ditemukan

In [16]:
# Membaca data secara lazy (LazyFrame)
lazy_df = pl.scan_csv(DATA_PATH)

# Menggunakan collect_schema() 
schema = lazy_df.collect_schema()
print("=== SKEMA DATASET ===")
for col_name, dtype in schema.items():
    print(f"- {col_name}: {dtype}")

# Menghitung baris dan kolom 
total_rows = lazy_df.select(pl.len()).collect().item()
total_cols = len(schema)

print(f"\nTotal Baris : {total_rows:,}")
print(f"Total Kolom : {total_cols}")

=== SKEMA DATASET ===
- Port Name: String
- State: String
- Port Code: Int64
- Border: String
- Date: String
- Measure: String
- Value: Int64
- Location: String

Total Baris : 346,733
Total Kolom : 8

In [9]:
print("5 Baris Pertama:")
display(lazy_df.head(5).collect())

print("5 Baris Terakhir:")
display(lazy_df.tail(5).collect())

5 Baris Pertama:

shape: (5, 8)
┌─────────────┬────────────┬───────────┬────────────┬────────────┬────────────┬───────┬────────────┐
│ Port Name   ┆ State      ┆ Port Code ┆ Border     ┆ Date       ┆ Measure    ┆ Value ┆ Location   │
│ ---         ┆ ---        ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---   ┆ ---        │
│ str         ┆ str        ┆ i64       ┆ str        ┆ str        ┆ str        ┆ i64   ┆ str        │
╞═════════════╪════════════╪═══════════╪════════════╪════════════╪════════════╪═══════╪════════════╡
│ Calexico    ┆ California ┆ 2507      ┆ US-Mexico  ┆ 03/01/2019 ┆ Trucks     ┆ 34447 ┆ POINT (-11 │
│ East        ┆            ┆           ┆ Border     ┆ 12:00:00   ┆            ┆       ┆ 5.48433000 │
│             ┆            ┆           ┆            ┆ AM         ┆            ┆       ┆ 000001     │
│             ┆            ┆           ┆            ┆            ┆            ┆       ┆ 32.…       │
│ Van Buren   ┆ Maine      ┆ 108       ┆ US-Canada  ┆ 03/01/2019 ┆ Rail       ┆ 428   ┆ POINT      │
│             ┆            ┆           ┆ Border     ┆ 12:00:00   ┆ Containers ┆       ┆ (-67.94271 │
│             ┆            ┆           ┆            ┆ AM         ┆ Full       ┆       ┆ 47.16207)  │
│ Otay Mesa   ┆ California ┆ 2506      ┆ US-Mexico  ┆ 03/01/2019 ┆ Trucks     ┆ 81217 ┆ POINT (-11 │
│             ┆            ┆           ┆ Border     ┆ 12:00:00   ┆            ┆       ┆ 7.05333    │
│             ┆            ┆           ┆            ┆ AM         ┆            ┆       ┆ 32.57333)  │
│ Nogales     ┆ Arizona    ┆ 2604      ┆ US-Mexico  ┆ 03/01/2019 ┆ Trains     ┆ 62    ┆ POINT (-11 │
│             ┆            ┆           ┆ Border     ┆ 12:00:00   ┆            ┆       ┆ 0.93361    │
│             ┆            ┆           ┆            ┆ AM         ┆            ┆       ┆ 31.3402799 │
│             ┆            ┆           ┆            ┆            ┆            ┆       ┆ 99…        │
│ Trout River ┆ New York   ┆ 715       ┆ US-Canada  ┆ 03/01/2019 ┆ Personal   ┆ 16377 ┆ POINT      │
│             ┆            ┆           ┆ Border     ┆ 12:00:00   ┆ Vehicle    ┆       ┆ (-73.44253 │
│             ┆            ┆           ┆            ┆ AM         ┆ Passengers ┆       ┆ 44.9900100 │
│             ┆            ┆           ┆            ┆            ┆            ┆       ┆ 000…       │
└─────────────┴────────────┴───────────┴────────────┴────────────┴────────────┴───────┴────────────┘

5 Baris Terakhir:

shape: (5, 8)
┌─────────────┬────────────┬───────────┬────────────┬────────────┬────────────┬───────┬────────────┐
│ Port Name   ┆ State      ┆ Port Code ┆ Border     ┆ Date       ┆ Measure    ┆ Value ┆ Location   │
│ ---         ┆ ---        ┆ ---       ┆ ---        ┆ ---        ┆ ---        ┆ ---   ┆ ---        │
│ str         ┆ str        ┆ i64       ┆ str        ┆ str        ┆ str        ┆ i64   ┆ str        │
╞═════════════╪════════════╪═══════════╪════════════╪════════════╪════════════╪═══════╪════════════╡
│ Norton      ┆ Vermont    ┆ 211       ┆ US-Canada  ┆ 01/01/1996 ┆ Personal   ┆ 9119  ┆ POINT      │
│             ┆            ┆           ┆ Border     ┆ 12:00:00   ┆ Vehicle    ┆       ┆ (-71.79    │
│             ┆            ┆           ┆            ┆ AM         ┆ Passengers ┆       ┆ 45.01)     │
│ Columbus    ┆ New Mexico ┆ 2406      ┆ US-Mexico  ┆ 01/01/1996 ┆ Personal   ┆ 29486 ┆ POINT      │
│             ┆            ┆           ┆ Border     ┆ 12:00:00   ┆ Vehicles   ┆       ┆ (-107.63   │
│             ┆            ┆           ┆            ┆ AM         ┆            ┆       ┆ 31.78)     │
│ Hansboro    ┆ North      ┆ 3415      ┆ US-Canada  ┆ 01/01/1996 ┆ Rail       ┆ 0     ┆ POINT      │
│             ┆ Dakota     ┆           ┆ Border     ┆ 12:00:00   ┆ Containers ┆       ┆ (-99.35    │
│             ┆            ┆           ┆            ┆ AM         ┆ Full       ┆       ┆ 49)        │
│ Calexico    ┆ California ┆ 2507      ┆ US-Mexico  ┆ 01/01/1996 ┆ Buses      ┆ 0     ┆ POINT      │
│ East        ┆            ┆           ┆ Border     ┆ 12:00:00   ┆            ┆       ┆ (-115.39   │
│             ┆            ┆           ┆            ┆ AM         ┆            ┆       ┆ 32.67)     │
│ Presidio    ┆ Texas      ┆ 2403      ┆ US-Mexico  ┆ 01/01/1996 ┆ Trucks     ┆ 347   ┆ POINT (-10 │
│             ┆            ┆           ┆ Border     ┆ 12:00:00   ┆            ┆       ┆ 4.39000000 │
│             ┆            ┆           ┆            ┆ AM         ┆            ┆       ┆ 000001     │
│             ┆            ┆           ┆            ┆            ┆            ┆       ┆ 29.…       │
└─────────────┴────────────┴───────────┴────────────┴────────────┴────────────┴───────┴────────────┘

In [15]:
con = duckdb.connect()

# Profiling statistik dengan DuckDB  membaca file CSV
summary_df = con.sql(f"SUMMARIZE SELECT * FROM read_csv_auto('{DATA_PATH}')").pl()
display(summary_df)

shape: (8, 12)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ column_nam ┆ column_typ ┆ min       ┆ max       ┆ … ┆ q50       ┆ q75       ┆ count  ┆ null_perc │
│ e          ┆ e          ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---    ┆ entage    │
│ ---        ┆ ---        ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ i64    ┆ ---       │
│ str        ┆ str        ┆           ┆           ┆   ┆           ┆           ┆        ┆ decimal[9 │
│            ┆            ┆           ┆           ┆   ┆           ┆           ┆        ┆ ,2]       │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ Port Name  ┆ VARCHAR    ┆ Alcan     ┆ Willow    ┆ … ┆ null      ┆ null      ┆ 346733 ┆ 0.00      │
│            ┆            ┆           ┆ Creek     ┆   ┆           ┆           ┆        ┆           │
│ State      ┆ VARCHAR    ┆ Alaska    ┆ Washingto ┆ … ┆ null      ┆ null      ┆ 346733 ┆ 0.00      │
│            ┆            ┆           ┆ n         ┆   ┆           ┆           ┆        ┆           │
│ Port Code  ┆ BIGINT     ┆ 101       ┆ 4105      ┆ … ┆ 3013      ┆ 3396      ┆ 346733 ┆ 0.00      │
│ Border     ┆ VARCHAR    ┆ US-Canada ┆ US-Mexico ┆ … ┆ null      ┆ null      ┆ 346733 ┆ 0.00      │
│            ┆            ┆ Border    ┆ Border    ┆   ┆           ┆           ┆        ┆           │
│ Date       ┆ TIMESTAMP  ┆ 1996-01-0 ┆ 2019-03-0 ┆ … ┆ 2007-03-2 ┆ 2012-09-0 ┆ 346733 ┆ 0.00      │
│            ┆            ┆ 1         ┆ 1         ┆   ┆ 5 08:26:5 ┆ 6 03:33:5 ┆        ┆           │
│            ┆            ┆ 00:00:00  ┆ 00:00:00  ┆   ┆ 3.027294  ┆ 6.283673  ┆        ┆           │
│ Measure    ┆ VARCHAR    ┆ Bus Passe ┆ Trucks    ┆ … ┆ null      ┆ null      ┆ 346733 ┆ 0.00      │
│            ┆            ┆ ngers     ┆           ┆   ┆           ┆           ┆        ┆           │
│ Value      ┆ BIGINT     ┆ 0         ┆ 4447374   ┆ … ┆ 91        ┆ 2489      ┆ 346733 ┆ 0.00      │
│ Location   ┆ VARCHAR    ┆ POINT     ┆ POINT (-9 ┆ … ┆ null      ┆ null      ┆ 346733 ┆ 0.00      │
│            ┆            ┆ (-100.05  ┆ 9.71915   ┆   ┆           ┆           ┆        ┆           │
│            ┆            ┆ 49)       ┆ 48.94208) ┆   ┆           ┆           ┆        ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

In [13]:
# 1. Cek persentase null tiap kolom menggunakan Polars expressions
null_audit = lazy_df.select([
    (pl.col(col).null_count() / pl.len() * 100).round(2).alias(f"{col}_null_pct")
    for col in schema.keys()
]).collect()

print("=== PERSENTASE NULL PER KOLOM (%) ===")
display(null_audit)

# 2. Cek baris duplikat penuh
total_unique = lazy_df.unique().select(pl.len()).collect().item()
duplicate_count = total_rows - total_unique

print(f"\nTotal Baris Unik     : {total_unique:,}")
print(f"Jumlah Baris Duplikat: {duplicate_count:,} ({(duplicate_count / total_rows) * 100:.2f}%)")

=== PERSENTASE NULL PER KOLOM (%) ===

shape: (1, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ Port Name_ ┆ State_null ┆ Port Code_ ┆ Border_nu ┆ Date_null ┆ Measure_n ┆ Value_nul ┆ Location_ │
│ null_pct   ┆ _pct       ┆ null_pct   ┆ ll_pct    ┆ _pct      ┆ ull_pct   ┆ l_pct     ┆ null_pct  │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ f64        ┆ f64        ┆ f64        ┆ f64       ┆ f64       ┆ f64       ┆ f64       ┆ f64       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ 0.0       │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

Total Baris Unik     : 346,733
Jumlah Baris Duplikat: 0 (0.00%)

In [14]:
PARQUET_PATH = "../data/processed/raw_data.parquet"

# Menyimpan langsung dari lazy plan tanpa memakan RAM besar
lazy_df.sink_parquet(PARQUET_PATH)

file_size_csv = os.path.getsize(DATA_PATH) / (1024 * 1024)
file_size_parquet = os.path.getsize(PARQUET_PATH) / (1024 * 1024)

print(f"File Parquet berhasil dibuat di: {PARQUET_PATH}")
print(f"Ukuran CSV Asli    : {file_size_csv:.2f} MB")
print(f"Ukuran Parquet Baru: {file_size_parquet:.2f} MB")
print(f"Efisiensi Kompresi : {(1 - file_size_parquet / file_size_csv) * 100:.2f}% lebih hemat")

File Parquet berhasil dibuat di: ../data/processed/raw_data.parquet
Ukuran CSV Asli    : 35.34 MB
Ukuran Parquet Baru: 1.97 MB
Efisiensi Kompresi : 94.43% lebih hemat